version: "2"
services:
  ca0:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org5
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7058
    ports:
      - "7058:7058"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d' 
    volumes:
      - ./organizations/fabric-ca/org5:/etc/hyperledger/fabric-ca-server
    container_name: ca_org5